version: 2

#  Copyright (C) 2019 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.
# 

# Configuration file for Circle CI 
# CI will report failure if any executed command returns and error status
# Operations performed are as follows
# Build source code
# Run unit tests for C++ 
# Run static code analyzer for SourceCloud
# Upload test results
# Every run command should start with source ${INIT_ENV} to ensure all default dependancies are available
jobs:
  build:
    # Pull docker image 
    # XTERM used for better catkin_make output
    docker:
      - image: v2xhub/V2X-Hub
        user: v2xhub
        environment:
          TERM: xterm
          
    # Set working directory
    working_directory: "/opt/v2xhub/"
    # Pull code and execute tests |
    # Name of each run command defines purpose use
    steps:
      #setup remote docker
      - setup_remote_docker :
          docker_layer_caching: true

    
      # Checkout PR branch
      - checkout
      - run:
          name: Build V2XHub and run it.  First, install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install docker-ce docket-ce-cli containerd.io
            sudo apt-get update
            sudo apt-get install lamp-server^
            # need to figure out how to enter password for lamp-server
            sudo docker build --network host 127.0.0.1 .
            # need to run the docker to actually run the docker to test it.
            sudo docker run --network host 127.0.0.1 tail -F



