version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: 'IVP'
      MYSQL_PASSWORD: 'ivpx1'
      MYSQL_ROOT_PASSWORD: 'ivpx1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  apache-php:
    image: php:7.2.2-apache
    container_name: apache_php
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    network_mode: host
    stdin_open: true
    tty: true

  # v2x-hub:
  #   image: itabrl/test:latest
  #   container_name: v2x-hub
  #   environment:
  #     MYSQL_DATABASE: IVP
  #     MYSQL_USER: IVP
  #     MYSQL_PASSWORD: 'ivpx1'
  #     MYSQL_ROOT_PASSWORD: ivpx1
  #   depends_on:
  #     - db
  #   restart: always
  #   network_mode: host