version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=IVP
      - MYSQL_USER=IVP
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
      spectrum_v2x_net:
        ipv4_address: 172.1.0.11
    healthcheck:
        test: out=$$(mysqladmin ping -hlocalhost -P3306 -uIVP --password=$$(cat $${MYSQL_PASSWORD_FILE}) 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
        timeout: 20s
        retries: 10
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - ./mysql/localhost.sql:/docker-entrypoint-initdb.d/localhost.sql
      - mysql-datavolume:/var/lib/mysql

  php:
    image: usdotfhwaops/php:k900
    container_name: php
    network_mode: service:db
    depends_on: 
      - db
      - v2xhub
    stdin_open: true
    tty: true

  v2xhub:
    image: usdotfhwaops/v2xhubamd:k900
    container_name: v2xhub
    network_mode: service:db
    restart: always
    depends_on:
        db:
            condition: service_healthy
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - ./logs:/var/log/tmx
      - ./MAP:/var/www/plugins/MAP

  db2:
    image: mysql:5.7
    container_name: mysql2
    restart: always
    environment:
      - MYSQL_DATABASE=IVP
      - MYSQL_USER=IVP
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
      spectrum_v2x_net2:
        ipv4_address: 172.2.0.12
    healthcheck:
        test: out=$$(mysqladmin ping -hlocalhost -P3306 -uIVP --password=$$(cat $${MYSQL_PASSWORD_FILE}) 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
        timeout: 20s
        retries: 10
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - ./mysql2/localhost2.sql:/docker-entrypoint-initdb.d/localhost2.sql
      - mysql-datavolume:/var/lib/mysql2

  php2:
    image: usdotfhwaops/php:k900
    container_name: php2
    network_mode: service:db2
    depends_on: 
      - db2
      - v2xhub2
    stdin_open: true
    tty: true

  v2xhub2:
    image: usdotfhwaops/v2xhubamd:k900
    container_name: v2xhub2
    network_mode: service:db2
    restart: always
    depends_on:
        db2:
            condition: service_healthy
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - ./logs:/var/log/tmx
      - ./MAP:/var/www/plugins/MAP

networks:
  spectrum_v2x_net:
    ipam:
      config:
        - subnet: 172.1.0.0/16

  spectrum_v2x_net2:
    ipam:
      config:
        - subnet: 172.2.0.0/16

secrets:
    mysql_password:
        file: ./secrets/mysql_password.txt
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt

volumes:
  mysql-datavolume:
