version: '3.4'

services:
  db:
    image: usdotfhwaops/v2x-mysql:v1.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=IVP
      - MYSQL_USER=IVP
      - MYSQL_PASSWORD=ivp
      - MYSQL_ROOT_PASSWORD=ivp
    network_mode: host
    volumes:
      - ./mysql/localhost.sql:/docker-entrypoint-initdb.d/database.sql

  php:
    image: php:7.2.2-apache
    container_name: php
    volumes:
      - ./php/:/var/www/html/
    network_mode: host
    depends_on: 
      - db
    stdin_open: true
    tty: true

  v2xhub:
    image: usdotfhwaops/v2x-hub:v3.2
    container_name: v2xhub
    network_mode: host
    depends_on: 
      - php
